### ISSUE TITLE
[Bug]: Modbus Remotecontrol not working after 2025.8 and doing Modification in case of Unknown Issue

### ISSUE THREAD

**Issue by flight1wer1** [wills106/homeassistant-solax-modbus#1585]
### Describe the bug

Since Update 2025.8.5 i got issues with the integration and "unknown Error" i have fixed this issue by doing some changes in the Files
this changes are mentioned on the commend 1551 https://github.com/wills106/homeassistant-solax-modbus/commit/2c0afcfc41e0be9d54a84cf0480d0a7ef9e41a97

But now, i can not to changes on all my 3 Solax Inverter. If i make the remote Control to change on "selfuse" and than i press the trigger, comes this issue:
Is this a known issue? is there a way to correct this also with a modifikation?
Thanks for supporting

Die Aktion button/press konnte nicht ausgeführt werden. ModbusClientMixin.write_registers() got an unexpected keyword argument 'slave'

Logger: custom_components.solax_modbus
Quelle: custom_components/solax_modbus/init.py:830
Integration: SolaX Inverter Modbus ([Dokumentation](https://homeassistant-solax-modbus.readthedocs.io/), [Probleme](https://github.com/wills106/homsassistant-solax-modbus/issues))
Erstmals aufgetreten: 18:33:31 (1 Vorkommnis)
Zuletzt protokolliert: 18:33:31

Something went wrong reading from modbus: ModbusClientMixin.write_registers() got an unexpected keyword argument 'slave'
Traceback (most recent call last):
File "/config/custom_components/solax_modbus/init.py", line 830, in async_read_modbus_data
res = await self.async_read_modbus_registers_all(group)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/solax_modbus/init.py", line 1093, in async_read_modbus_registers_all
await self.async_write_registers_multi(
...<3 lines>...
)
File "/config/custom_components/solax_modbus/init.py", line 817, in async_write_registers_multi
resp = await self._client.write_registers(address=address, values=payload, **kwargs)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModbusClientMixin.write_registers() got an unexpected keyword argument 'slave'

BR
Thorsten

### Integration Version

2025.8.7

### Homeassistant core version

2025.8

### Inverter brand

Solax X3 Hybrid

### Plugin used

plugin_solax.py

### Serial prefix

n.A.

### Inverter firmware versions

latest

### Connection Method

WIFI 3.0

### Dongle firmware

latest 

### Detailed Error Log

_No response_

### Additional context

_No response_

**Comment by infradom** [comment]
Sorry, we are working on a version that makes the integration fully compatible with the newer pymodbus versions.
Your modifications  may not have been tested sufficiently, solving your problem would  distract us from our work that should solve your original issue. 
Sorry again, but I want to get the correct solution for pymodbus released as soon as possible. I am in the (initial) testing phase right now.

If you submit a bug report related to pymodbus issues (including the Endian/payload stuff), you should at least provide your pymodbus version or a debug log that includes a restart.

Sorry, I will ignore your bug report and continue my work on the final solution

**Comment by flight1wer1** [comment]
Hi @infradom, please no sorry. (: I fully understand. 
But just for understanding. If i delete the integration and make a fully new download, i should have the new pymodbus or i am wrong? because this brings me to the modification from the answer in 1551. 
Where can i find the pymodbus file?

should the solax integration work with 2025.9 Beta?

**Comment by infradom** [comment]
sorry, you will have to wait until we release the new modbus code. Testing is proceeding very well ...

**Comment by rosenrot00** [comment]
@flight1wer1 could you give the latest release a try to see if it works for you? In case not could you tell your pymodbus version that is installed in your HA environment?

**Comment by flight1wer1** [comment]
@rosenrot00,

i have the new integration working. With the remotecontrol is not working.
Iam not sure where to find the pymodbus version. When i read the files in
the Solax integration i read 3.8.3.

if you tell me how i find a new one and how to install, i will try.

Thanks
Thorsten


Am Mi., 3. Sept. 2025 um 10:32 Uhr schrieb rosenrot00 <
***@***.***>:

**Comment by rosenrot00** [comment]
@flight1wer1 should work with the latest release now. Please let us know and close if it is resolved.

**Comment by flight1wer1** [comment]
Goodmorning!

Use HA 2025.9 and Solax latest version. It is now running perfectly!!!

Thanks so much for your effort!!!
Thorsten

Am Do., 4. Sept. 2025 um 08:57 Uhr schrieb rosenrot00 <
***@***.***>:

**Comment by rosenrot00** [comment]
Great. Thanks for testing. Please close it then.

**Comment by wills106** [comment]
Closing as complete.
